spring:
  cloud:
    gateway:
      routes:
        - id: shopping-list
          uri: http://127.0.0.1:5000
          predicates:
            - Path=/api/**
      httpclient:
        ssl:
          useInsecureTrustManager: true